[package]
name = "degauss"
version = "0.1.0"
edition = "2018"
authors = ["Theo B. <vertexclique@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
avro-rs = "0.13"
structopt = { version = "0.3", features = [ "paw" ] }
paw = "1.0"
strum = "0.22.0"
strum_macros = "0.22.0"
comfy-table = "4.1.1"